root: true
env:
  node: true
  es6: true
  commonjs: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
  - import
  - prettier
extends:
  - airbnb-typescript-prettier
rules:
  prettier/prettier: error
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - warn
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
      caughtErrorsIgnorePattern: '^_'
  '@typescript-eslint/no-use-before-define': warn
  '@typescript-eslint/no-var-requires': 'off'
  '@typescript-eslint/no-empty-function': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  global-require: 'off'
  guard-for-in: 'off'
  no-underscore-dangle: 'off'
  no-restricted-syntax: 'off'
  class-methods-use-this: 'off'
  lines-between-class-members: 'off'
  no-continue: 'off'
  no-console: 'off'
  import/prefer-default-export: 'off'
  quotes: ['error', 'single']
  indent:
    - error
    - 2
    - SwitchCase: 1
  max-len:
    - error
    - code: 256
  no-plusplus:
    - error
    - allowForLoopAfterthoughts: true
