"""create BattleLog table

Revision ID: 7b48a8c5bf8c
Revises: 2fb30ee1aded
Create Date: 2021-12-13 14:48:25.124007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b48a8c5bf8c'
down_revision = '2fb30ee1aded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battlelog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gameToken', sa.String(length=100), nullable=True),
    sa.Column('winnerId', sa.Integer(), nullable=True),
    sa.Column('loserId', sa.Integer(), nullable=True),
    sa.Column('isDraw', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.String(length=20), nullable=True),
    sa.Column('battleTime', sa.Integer(), nullable=True),
    sa.Column('isSingleMode', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battlelog')
    # ### end Alembic commands ###
