"""change column names to camelCase

Revision ID: 2fb30ee1aded
Revises: 52d53d32a5b3
Create Date: 2021-12-12 23:53:25.410865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb30ee1aded'
down_revision = '52d53d32a5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accesslog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.String(length=20), nullable=True))
        batch_op.drop_column('user_id')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tokentable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userId', sa.Integer(), nullable=True))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('userName', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('userPassword', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('createdAt', sa.String(length=20), nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('user_password')
        batch_op.drop_column('auth_token')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('auth_token', sa.VARCHAR(length=63), nullable=True))
        batch_op.add_column(sa.Column('user_password', sa.VARCHAR(length=64), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('createdAt')
        batch_op.drop_column('userPassword')
        batch_op.drop_column('userName')

    with op.batch_alter_table('tokentable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('userId')

    with op.batch_alter_table('accesslog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_column('createdAt')
        batch_op.drop_column('userId')

    # ### end Alembic commands ###
