# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protobuf/websocket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protobuf/websocket.proto',
  package='protobuf',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x18protobuf/websocket.proto\x12\x08protobuf\"\t\n\x07\x43loseWs\"?\n\x0cWsReqWrapper\x12$\n\x07\x63losews\x18\x01 \x01(\x0b\x32\x11.protobuf.CloseWsH\x00\x42\t\n\x07\x63ontent\"@\n\rWsRespWrapper\x12$\n\x07\x63losews\x18\x01 \x01(\x0b\x32\x11.protobuf.CloseWsH\x00\x42\t\n\x07\x63ontent')
)




_CLOSEWS = _descriptor.Descriptor(
  name='CloseWs',
  full_name='protobuf.CloseWs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=47,
)


_WSREQWRAPPER = _descriptor.Descriptor(
  name='WsReqWrapper',
  full_name='protobuf.WsReqWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='closews', full_name='protobuf.WsReqWrapper.closews', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='protobuf.WsReqWrapper.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=49,
  serialized_end=112,
)


_WSRESPWRAPPER = _descriptor.Descriptor(
  name='WsRespWrapper',
  full_name='protobuf.WsRespWrapper',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='closews', full_name='protobuf.WsRespWrapper.closews', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='content', full_name='protobuf.WsRespWrapper.content',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=114,
  serialized_end=178,
)

_WSREQWRAPPER.fields_by_name['closews'].message_type = _CLOSEWS
_WSREQWRAPPER.oneofs_by_name['content'].fields.append(
  _WSREQWRAPPER.fields_by_name['closews'])
_WSREQWRAPPER.fields_by_name['closews'].containing_oneof = _WSREQWRAPPER.oneofs_by_name['content']
_WSRESPWRAPPER.fields_by_name['closews'].message_type = _CLOSEWS
_WSRESPWRAPPER.oneofs_by_name['content'].fields.append(
  _WSRESPWRAPPER.fields_by_name['closews'])
_WSRESPWRAPPER.fields_by_name['closews'].containing_oneof = _WSRESPWRAPPER.oneofs_by_name['content']
DESCRIPTOR.message_types_by_name['CloseWs'] = _CLOSEWS
DESCRIPTOR.message_types_by_name['WsReqWrapper'] = _WSREQWRAPPER
DESCRIPTOR.message_types_by_name['WsRespWrapper'] = _WSRESPWRAPPER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CloseWs = _reflection.GeneratedProtocolMessageType('CloseWs', (_message.Message,), dict(
  DESCRIPTOR = _CLOSEWS,
  __module__ = 'protobuf.websocket_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.CloseWs)
  ))
_sym_db.RegisterMessage(CloseWs)

WsReqWrapper = _reflection.GeneratedProtocolMessageType('WsReqWrapper', (_message.Message,), dict(
  DESCRIPTOR = _WSREQWRAPPER,
  __module__ = 'protobuf.websocket_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.WsReqWrapper)
  ))
_sym_db.RegisterMessage(WsReqWrapper)

WsRespWrapper = _reflection.GeneratedProtocolMessageType('WsRespWrapper', (_message.Message,), dict(
  DESCRIPTOR = _WSRESPWRAPPER,
  __module__ = 'protobuf.websocket_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.WsRespWrapper)
  ))
_sym_db.RegisterMessage(WsRespWrapper)


# @@protoc_insertion_point(module_scope)
