
name: Discord Message Notify

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "deploy"
        description: "Build and deploy to GitHub Pages"
        color: 0x0000ff
        username: GitHub Actions
