# This is a basic workflow to help you get started with Actions

name: Game Server on Azure

# Controls when the workflow will run
on:
  push:
    branches:
      - main
    paths:
      - "app/*"
      - ".github/workflows/server.yml"
  pull_request:
    branches:
      - main
    paths:
      - "app/*"
      - ".github/workflows/server.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ACG-game-server
  AZURE_WEBAPP_PACKAGE_PATH: '.'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    # Install all Requirements and Setup Environment for Python Development
    - name: Initialize Environment
      run: |
        sudo apt install -y protobuf-compiler
        bash run-backserver.sh --init -y -y


    # Run All test
    - name: Test
      run: bash run-backserver.sh --test
    
    # Start Up backend server
    - name: Start server
      run: bash run-backserver.sh --startup

    - name: Building web app
      uses: azure/appservice-build@v2
    - name: Deploy web App using GH Action azure/webapps-deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        # package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "Server Deploy to Azure App Servise"
        status: ${{ job.status }}
        nofail: false
        nodetail: false
        description: "Build and deploy to GitHub Pages"
        username: GitHub Actions
