name: NodeJS with Webpack

on:
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/webpack.yml"
  pull_request:
    branches:
      - main
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Assign memory
      run: export NODE_OPTIONS="--max-old-space-size=6144"
    - name: Install packages
      run: npm install
    - name: Build
      run: |
        npm run build-noeditor
        npm run pack
    - name: App Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist
    - uses: sarisia/actions-status-discord@v1
      if: always()
      with:
        webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
        title: "Deploy BabylonJS App"
        status: ${{ job.status }}
        nofail: false
        nodetail: false
        description: "Build and deploy to GitHub Pages"
        username: GitHub Actions
